### ISSUE TITLE
Multiple doors

### ISSUE THREAD

**Issue by relic982** [apexad/node-iris-aladdin-connect-garage-door#1]
Would love to see this support multiple doors.

**Comment by apexad** [comment]
This should actually be pretty easy. I’ll try and work on it soon.

**Comment by relic982** [comment]
Fantastic. Thank you so much! It's one of the few things missing from my homekit. Now if Nexia would just give me an API... : (

**Comment by apexad** [comment]
Alright, I've added an optional parameter so you can specify device name.  
This is the name that you should see in the Iris App.

I assume you want me to update https://www.npmjs.com/package/homebridge-garagedoor-command as well so you can have multiple doors with that too? or is this good?  Go ahead and close the issue if this is all you need.

**Comment by relic982** [comment]
Dude, that was quick. : )

Your assumptions are spot on. If you could update the home bridge-garagedoor-command module, you would be my hero.

Thank you so much for your work here.

**Comment by apexad** [comment]
So, the quickest way to make this happen is to follow these steps:
1. Make a copy of the homebridge-garage door-command folder within your node_modules folder.
2. Change `
  homebridge.registerAccessory('homebridge-garagedoor-command', 'GarageCommand', GarageCmdAccessory);` in index.js adding a 2 to homebridge-garage door-command and GarageCommand
3. Add a new accessory to homebridge config.json with name GarageCommand2.

Then it’s just a matter of running npm update where your commands are setup and making a script for each action of each garage door.

**Comment by relic982** [comment]
Thank you sir.

It is working perfectly. I appreciate all of your work.

**Comment by apexad** [comment]
FYI, I just figured out that homebridge supports calling the same accessory twice with a different name, so the whole copying of the plugin part is actually not needed.
