### ISSUE TITLE
A little Configuration help

### ISSUE THREAD

**Issue by Aviator85** [apexad/node-iris-aladdin-connect-garage-door#2]
I have an RPI3 setup and working with homebridge.
I have tp-link smart plugs, Nest, and Honey Comfort Connect setup and working so I do know some stuff but I just cant wrap my head around this configuration to work with this.

I have:
All dependencies listed installed
Lowes Iris account setup and linked with my aladdin connect door control module
I've installed the node-iris-aladdin-connect-garage-door
I've installed and tried to tie it in with homebridge-garagedoor-command

Im not a programmer by trade but very tech savy and just need a little help, would be very much appreciated. 

![img_6879](https://user-images.githubusercontent.com/37892009/38071314-38ea0a16-32e6-11e8-99b6-7efe398f0b04.jpeg)

**Comment by relic982** [comment]
Did you modify the open, close and state script locations and contents in the config?

**Comment by Aviator85** [comment]
I modified the open, close, and state.js in the example folder with my login credentials. After that I was just shooting in the dark. I wasn't sure if i was supposed to take them out of the example folder and place them in the main node folder. Then I was reading the short conversation about installing homebridge-garagedoor-command and placing the .js files into that folder and when I do and edit the homebridge config it doesn't work. So I guess my main questions are where do I properly place the .js files and what portion of code do I add to my homebridge config because at this point im just guessing. Got a 7 week old baby lack sleep any and all help is appreciated.

**Comment by relic982** [comment]
I run my homebridge on a Mac. I put the scripts into a folder called garage inside of the homebridge directory.

See below for my config.json addition:

      "accessory": "GarageCommand",
      "name": "Large Garage Door",
      "open": "node /Users/name/.homebridge/garage/open.js",
      "close": "node /Users/name/.homebridge/garage/close.js",
      "state": "node /Users/name/.homebridge/garage/state.js",
      "status_update_delay": 20

I feel your pain with the kid. I put this together when my son was about 2 months old.

He didn’t start sleeping the night until after he was 13 months.

Does this help or do you have any other questions for the configuration?

**Comment by Aviator85** [comment]
Okay, well, another step closer.... I think. So I have two plugins ; homebridge-garagedoor-command installed and the node-iris-aladdin-connect-garage-door plugin.

Last night I was thinking that when the garage-command "triggered" it called on the aladdin connect to connect to lowe-iris  -> im just rambling. Okay so I tried to make sense of your config and heres what I got:

My config:

"accessories": [
        {
            "accessory": "GarageCommand",
            "name": "Garage Door",
            "open": "node /home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/open.js",
            "close": "node /home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/close.js",
            "state": "node /home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/state.js",
            "status_update_delay": 15
        }
    ],

And the errors in the log:

[2018-3-30 00:28:13] [Garage Door] Error: Error: Command failed: node /home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/state.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/state.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

[2018-3-30 00:28:13] [Garage Door] Error: Error: Command failed: node /home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/state.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/state.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

![img_5193](https://user-images.githubusercontent.com/37892009/38120603-a2871b18-338f-11e8-8fe0-af7252a88284.PNG)

**Comment by relic982** [comment]
What the garage-command does is call upon the scripts.

The noe-iris-aladdin is about providing the scripts. Those scripts can live anywhere so long as homebridge has permission to them. That is why I put them in a separate folder and called upon the full path.

Check your permissions on the scripts. Make sure homebridge can access them and they have the x bit set.

sudo chmod +x /home/pi/homebridge/config/node_modules/homebridge-garagedoor-command/*

**Comment by Aviator85** [comment]
I do have my login credentials saved into each individual open, close, and state.js. Do I need to change any other configuration files in the node-iris-aladdin-connect-garage-door folder like the index.js or package.js?

**Comment by relic982** [comment]
No, those two files can remain unchanged.

**Comment by Aviator85** [comment]
Permissions are good, I ran the x bit command, even tried changing my main config file removing the "/home/pi" from the file path - not sure if homebridge has its own shell within itself - on the pi it has a webinterface and can open terminal. All that being saidI still get the same errors. Its probably something really dumb that i'm doing.

**Comment by relic982** [comment]
The only other thing I can recommend is moving the contents of the folder containing the .js scripts to another location in the file system and try pointing the config.json to the new location.

This really sounds like a permissions issue. 

I know running the Homebridge on a pi gave me some strange permission issues from time to time. 

T

**Comment by Aviator85** [comment]
Yeah, I'll mess around with it, I appreciate the help.

**Comment by Aviator85** [comment]
I think your right because it executed beautifully in the terminal.... Gave the state, opened and closed as advertised.... so annoying...

/homebridge # node /homebridge/node_modules/homebridge-garagedoor-command/state.js
CLOSED
/homebridge # node /homebridge/node_modules/homebridge-garagedoor-command/open.js
OPENING
/homebridge # node /homebridge/node_modules/homebridge-garagedoor-command/close.js
CLOSING
/homebridge #

**Comment by Aviator85** [comment]
omfg.... Yup... went full retard on this. enjoy:

So being a lazy typer, I was VNC'd into my pi and copied the path and pasted it into my config, well, just like I was saying earlier homebridge has its own built in terminal and was showing a different path but hard to catch the difference 

 node /homebridge/node_modules/homebridge-garagedoor-command/state.js
vs
node /homebridge/**config**/node_modules/homebridge-garagedoor-command/state.js

Nothing like shooting yourself in the foot huh!? Gotta pay attention to detail, I told you it was something I was doing dumb. Hey, like I said I'm not a programer by trade but I can scrape together some crap sometimes with the help of fine helping folks like yourself! 

![image-1](https://user-images.githubusercontent.com/37892009/38120617-b9d00fb4-338f-11e8-91f5-7185d2605b04.png)

**Comment by Aviator85** [comment]
Now the only other thing that would be nice to get on this is the coffee maker thats built into the refrigerator on the homebridge that'd be REAL nice. Thanks again!

**Comment by relic982** [comment]
Haha. Glad you got it working. 

Cheers. 

Enjoy!

T
