### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Aviator85** [apexad/node-iris-aladdin-connect-garage-door#4]
Man, hate to be the squeaky wheel lol... So my raspberry pi crashed months ago and just now getting around to getting back how I had homebridge setup before. Everything works except for this dang Garage door. I set it up exactly the same as before but now im getting this syntax error and I've looked at my state.js and I don't see anything on line 1 that got messed up - aggravating lol - any help is much appreciated 

Here is the error I get
<img width="1020" alt="screen shot 2018-11-20 at 10 33 20 pm" src="https://user-images.githubusercontent.com/37892009/48819226-887fb600-ed14-11e8-912b-7864ae4e781b.png">

Here is my state.js
<img width="942" alt="screen shot 2018-11-20 at 10 34 08 pm" src="https://user-images.githubusercontent.com/37892009/48819236-96353b80-ed14-11e8-9eb0-bdce5af2126c.png">

And here is when I run it manually thru terminal
<img width="1024" alt="screen shot 2018-11-20 at 10 32 56 pm" src="https://user-images.githubusercontent.com/37892009/48819255-ab11cf00-ed14-11e8-8f05-736ea2b82bd7.png">

**Comment by relic982** [comment]
Can you show your config.json file and blank out your email and pw?

**Comment by Aviator85** [comment]
<img width="1435" alt="screen shot 2018-11-21 at 9 40 23 am" src="https://user-images.githubusercontent.com/37892009/48851900-d080f600-ed71-11e8-880a-3ce3f44d54a1.png">

**Comment by relic982** [comment]
Thanks. I see your problem. You are missing the node command.

The lines should read:

"open": "node /homebridge/node_modules/homebridge-garagedoor-command/open.js",
"close": "node /homebridge/node-modules/homebridge-garagedoor-command/close.js",
"state": "node /homebridge/node-modules/homebridge-garagedoor-command/state.js"

Cheers!

**Comment by Aviator85** [comment]
GAH! devil in the details. Appreciate it. 👍

**Comment by apexad** [comment]
Just to comment, I would advise moving the node scripts to a folder outside of node_modules. You may accidentally delete the files more easily with them there.

Otherwise, glad you got it working!
