### ISSUE TITLE
Iris is dead

### ISSUE THREAD

**Issue by ghost** [apexad/node-iris-aladdin-connect-garage-door#5]
Lowe’s has shutdown iris platform so this plugin stopped working from 04/01/2019. 

Are there any possible alternatives? I really like your plugin, made opening garage much easier. 

Thanks.

**Comment by apexad** [comment]
Yes, I will update the readme that this no longer works shortly.

Unfortunately I do not have an alternative way to access the garage door at this time.

**Comment by relic982** [comment]
I would recommend using the Insignia garage door openers from Best Buy. They have worked well for me.

**Comment by apexad** [comment]
I’m hoping I can figure out the exosite api and still use the same hardware. If I cannot do that I plan on making my own with a pi zero.

**Comment by ghost** [comment]
Insignia looks like a good alternative for now. Just placed an order. I’ll probably sell my AladdinConnect kit. 

Thanks!

**Comment by apexad** [comment]
Want to leave this open until I update the readme. Is there or script (or plugin) on GitHub that can be used with the insignia garage door opener?

**Comment by ghost** [comment]
It looks like Insignia has native support for Apple HomeKit

**Comment by apexad** [comment]
Alright, README has been updated.  I am not giving up on my Aladdin Connect and for now just switched it to the default service.  Bummer that I cannot use it with Siri/HomeKit/homebridge currently, but I will work on this or make my own controller as I mentioned earlier.

**Comment by apexad** [comment]
About to test this now, but this looks promising:

https://github.com/shoejosh/aladdin-connect
Uses the Aladdin connect/default service instead of iris

**Comment by apexad** [comment]
@ysquared2 may want to return that Insignia one.  I should have the above python script converted to a node-js version by the end of tomorrow, if not a lot sooner.

**Comment by ghost** [comment]
Awesome!!! I didn’t even know this api exists.

**Comment by apexad** [comment]
Neither did I until I finally had time to research this today.  You'll need to reset your Genie Aladdin Connect and get it setup in the Stand alone app.

**Comment by apexad** [comment]
I've got it working, just opened and closed my garage door with a node script again. It feels good.
Just need to work on cleaning up the code a bit and want to make it work a little more similar to how this version worked so it is essentially a drop in replacement after everyone switches their garage door over to the default service.

It will be at https://github.com/apexad/node-aladdin-connect-garage-door by end of day tomorrow.

Re-opening this issue until new version is up.

**Comment by apexad** [comment]
new version is up and working for me.  README on this repo updated again too!

**Comment by ghost** [comment]
Awesome!!! It worked for me!
